# Generated by Django 4.2.14 on 2024-09-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
