# Generated by Django 4.2.14 on 2024-09-19 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
